#!/usr/bin/env bash
#
# Syto quick start.
#
# Fetches one published model run (plus the data it needs) from the Hugging Face
# deposit, writes an inference config for the first RRBS sample in the deposit,
# and deconvolutes it.
#
#   ./quickstart.sh
#
# Everything lands in ./syto-data (override with SYTO_DATA_ROOT).  Roughly 5 GB
# is downloaded and 5 GB unpacked; the inference itself takes about ten seconds,
# on GPU or CPU alike -- no GPU is needed for this run.
#
set -euo pipefail

REPO_ID="CompEpigen/syto.1.0"
DATA_ROOT="${SYTO_DATA_ROOT:-$PWD/syto-data}"
RUN="cancer_detector__uniform"          # the published model run we use
READS_DIR="tier4-source-data/rrbs-recovered-reads/U250.l4.hg19"

# Archive paths inside the dataset repo.  Members keep their path relative to
# the deposit root, so unzipping them all into one directory restores the layout
# the published configs expect.
ARCHIVES=(
  "tier0-results/SYTO_tier0_results_mappings_v1.zip"                                                   # labels_dict.json (12 KB)
  "tier1-models/ood-rrbs/SYTO_tier1_models_oodrrbs_cancerdetector_uniform_v1.zip"                      # classifier + deconvolvers + calibrators (344 MB)
  "tier2-pseudobulks/ood-rrbs/SYTO_tier2_pseudobulks_oodrrbs_cancerdetector_uniform_v1.zip"            # pseudobulks, for the cell-type prior (3.2 GB)
  "tier3-training-data/SYTO_tier3_trainingdata_atlases_v1.zip"                                         # atlases (4.7 MB)
  "tier4-source-data/rrbs-recovered-reads/SYTO_tier4_sourcedata_rrbsrecoveredreads_U250l4hg19_v1.zip"  # 522 RRBS samples as recovered reads (1.2 GB)
)

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
die() { printf '\033[31merror: %s\033[0m\n' "$*" >&2; exit 1; }

# ── 0. prerequisites ─────────────────────────────────────────────────────────
command -v unzip >/dev/null || die "unzip not found"
command -v syto  >/dev/null || die "syto not found - run 'poetry install' and activate the environment"
if ! command -v hf >/dev/null; then
  die "hf not found - install it with 'pip install -U huggingface_hub'"
fi

# ── 1. authenticate ──────────────────────────────────────────────────────────
say "Hugging Face authentication"
if hf auth whoami >/dev/null 2>&1; then
  echo "already logged in as $(hf auth whoami | head -1)"
else
  echo "A Hugging Face account is needed to download the deposit."
  echo "Create a read token at https://huggingface.co/settings/tokens, then paste it below."
  hf auth login
fi

# ── 2. download and unpack ───────────────────────────────────────────────────
mkdir -p "$DATA_ROOT/.archives" "$DATA_ROOT/.unpacked"
for archive in "${ARCHIVES[@]}"; do
  name="$(basename "$archive")"
  marker="$DATA_ROOT/.unpacked/$name"
  if [ -f "$marker" ]; then
    echo "skipping $name (already unpacked)"
    continue
  fi

  say "Downloading $name"
  hf download "$REPO_ID" "$archive" --repo-type dataset --local-dir "$DATA_ROOT/.archives"

  say "Unpacking $name"
  unzip -qo "$DATA_ROOT/.archives/$archive" -d "$DATA_ROOT"
  touch "$marker"
  # The zip is only a container; drop it so the footprint stays at one copy.
  # Set SYTO_KEEP_ARCHIVES=1 to keep the downloads instead.
  [ "${SYTO_KEEP_ARCHIVES:-0}" = "1" ] || rm -f "$DATA_ROOT/.archives/$archive"
done

# ── 3. compose the inference config ──────────────────────────────────────────
cd "$DATA_ROOT"

# Every path below is relative to the deposit root, which is why the run happens
# from inside $DATA_ROOT.
SAMPLE_PATH="$(find "$READS_DIR" -name '*_reads.parquet' | sort | head -1)"
[ -n "$SAMPLE_PATH" ] || die "no recovered-reads parquet found under $DATA_ROOT/$READS_DIR"
SAMPLE="$(basename "$SAMPLE_PATH" _reads.parquet)"
OUT_DIR="outputs/quickstart/$SAMPLE"
CONFIG="quickstart_inference.yaml"

say "Writing $CONFIG for sample $SAMPLE"
MODEL="tier1-models/ood-rrbs/$RUN"
FEATURES="$MODEL/deconvolution/top_156_features"
CALIB="$MODEL/calibration/top_156_features"

cat > "$CONFIG" <<YAML
# Generated by quickstart.sh - run from the deposit root:
#   syto inference --config $CONFIG
labels_dict_path: tier0-results/mappings/labels_dict.json
num_labels: 39

# Read-level classifier: assigns each read a cell-type distribution.
classifier:
  classifier_type: cancer_detector
checkpoint_path: $MODEL/classifier/cancer_detector.joblib
features_mask_path: $FEATURES/features_mask_1.356686482834322_cutoff.npz

deconvolution:
  syto:
    atlas_path: tier3-training-data/atlases/Atlas.U25.l4.hg19.full.tsv
    atlas_name: U25.l4.hg19
    methods:
    - name: xgboost
      enabled: true
      use_callibration: true
      checkpoint_path: $FEATURES/xgb_deconvolver.joblib
      calibrators_dir: $CALIB/xgb_calibrators_and_predictions/
    - name: 3Layer_MLP
      enabled: true
      use_callibration: true
      checkpoint_path: $FEATURES/mlp_best_deconvolver.pt
      metadata_path: $FEATURES/mlp_architecture_meta.json
      calibrators_dir: $CALIB/mlp_calibrators_and_predictions/
    - name: Shallow_Wide_Network
      enabled: true
      use_callibration: true
      checkpoint_path: $FEATURES/swn_best_deconvolver.pt
      metadata_path: $FEATURES/swn_architecture_meta.json
      calibrators_dir: $CALIB/swn_calibrators_and_predictions/
    - name: ls
      flavor: nnls
      enabled: true
      use_callibration: true
      checkpoint_path: $FEATURES/nnls_deconvolver.joblib
      calibrators_dir: $CALIB/nnls_calibrators_and_predictions/
    - name: ls
      flavor: psls
      enabled: true
      use_callibration: true
      checkpoint_path: $FEATURES/psls_deconvolver.joblib
      calibrators_dir: $CALIB/psls_calibrators_and_predictions/

# The deposit ships reads already recovered from the BAMs, so inference starts
# at the classification stage.  Use 'type: bam' with 'data_path: sample.bam' to
# start from a BAM instead.
input:
  type: parsed_reads
  data_path: $SAMPLE_PATH
  chromosomes: all

# Atlas regions with no coverage are blended towards the prior read from the
# pseudobulk store below.
fill_in_missing_labels: true
missing_label_strategy: prior_blending
pseudobulk_path: tier2-pseudobulks/ood-rrbs/$RUN/pseudobulk_columnar

max_sequence_length: 160
prediction_batch_size: 2200

output_dir: $OUT_DIR
output:
  save_processed_reads: false
  save_predictions: false
  save_deconvolution: true
  visualization:
    enabled: true
    top_n: 10
YAML

# ── 4. run ───────────────────────────────────────────────────────────────────
say "Running inference on $SAMPLE"
syto inference --config "$CONFIG"

say "Done"
cat <<EOF
Results for $SAMPLE:

  $DATA_ROOT/$OUT_DIR/deconvolution_results.csv   cell-type proportions, one row per method
  $DATA_ROOT/$OUT_DIR/deconvolution_report.pdf    same, as a report
  $DATA_ROOT/$OUT_DIR/$CONFIG                     the config this run used

To deconvolute another sample, edit input.data_path in
$DATA_ROOT/$CONFIG (522 samples are available under $READS_DIR)
and rerun from $DATA_ROOT:

  syto inference --config $CONFIG
EOF
