"""Template mode: generate whole configs up-front, fill in the paths later.

The fine-grained mode asks for every value and writes one ready-to-run config.
Template mode instead materialises the *shape* of one or more task configs in a
single step: known defaults are written as-is, values that can only come from
the user (data paths, checkpoints, output dirs) become ``<placeholder>`` markers
to edit in a text editor, and the variable-length sections are pre-populated
with every available option (all deconvolvers, all baselines, all splits) so
unwanted entries are deleted rather than typed out.

A template is derived from the same ``field_specs`` the interactive mode drives,
so the two can never drift. Per-task specifics — which architecture branch to
materialise, what to put in a list section — come from an optional
``template_overrides(classifier)`` method on the task wizard.
"""

from syto.app.wizard.config_utils import is_placeholder, placeholder
from syto.app.wizard.fields import FieldSpec
from syto.app.wizard.tasks import TASK_REGISTRY

# Pipeline order, so the checkbox reads like the workflow rather than the
# alphabet. Tasks registered later but missing here are appended alphabetically.
TASK_ORDER = [
    "classifier_fit",
    "generate_pseudobulk",
    "fit_deconvolution",
    "fit_calibration",
    "deconvolute_pseudobulk",
    "inference",
]

# Tasks whose config shape depends on which classifier is being targeted.
CLASSIFIER_TASKS = {"classifier_fit", "generate_pseudobulk", "inference"}

# Superset of the architectures the classifier-dependent tasks accept; a task
# that supports fewer says so itself (see GeneratePseudobulkWizard).
CLASSIFIERS = ["dismir", "methylbert", "cancer_detector", "lookup", "epigenbert2"]


def ordered_tasks() -> list[str]:
    """Registered task names in pipeline order."""
    known = [name for name in TASK_ORDER if name in TASK_REGISTRY]
    return known + sorted(set(TASK_REGISTRY) - set(known))


def needs_classifier(tasks) -> bool:
    """True when at least one selected task branches on the classifier."""
    return any(task in CLASSIFIER_TASKS for task in tasks)


def template_value(spec: FieldSpec):
    """Value written for a single field in a template.

    A default is a working value and is kept. Otherwise the field is one the
    user must decide: a select collapses to its first choice (all options stay
    discoverable in the wizard), and anything else becomes a placeholder.
    """
    if spec.default is not None:
        return spec.default
    if spec.kind == "select" and spec.choices:
        return spec.choices[0]
    if spec.kind == "bool":
        return False
    return placeholder(spec.key)


def build_template(wizard, classifier: str | None = None) -> dict:
    """Build one task's template config.

    Walks the task's ``field_specs`` exactly as the engine does — the same
    ``when`` predicates against the answers accumulated so far — but supplies
    values non-interactively. List sections contribute nothing unless the task's
    ``template_overrides`` provides their content.
    """
    hook = getattr(wizard, "template_overrides", None)
    overrides = (hook(classifier) or {}) if hook is not None else {}

    answers: dict = {}
    for spec in wizard.field_specs():
        if spec.when is not None and not spec.when(answers):
            continue
        if spec.key in overrides:
            answers[spec.key] = overrides[spec.key]
            continue
        if spec.kind == "list_section":
            continue
        answers[spec.key] = template_value(spec)
    return wizard.build_config(answers)


def count_placeholders(node) -> int:
    """Number of ``<placeholder>`` markers anywhere in a config tree."""
    if isinstance(node, dict):
        return sum(count_placeholders(value) for value in node.values())
    if isinstance(node, list):
        return sum(count_placeholders(item) for item in node)
    return 1 if is_placeholder(node) else 0


def header(task: str, path: str, classifier: str | None = None) -> str:
    """Comment block prepended to a generated template file."""
    rule = "# " + "-" * 73
    lines = [
        rule,
        f"# {task} config template (generated by `syto create-config`)",
    ]
    if classifier is not None and task in CLASSIFIER_TASKS:
        lines.append(f"# Target classifier: {classifier}")
    lines += [
        "#",
        "# Every <angle-bracketed> value is a placeholder you must replace before",
        "# running; everything else is a working default you can tune. Sections",
        "# list every available option — delete the entries you do not want.",
        "#",
        "# Run with:",
        f"#   syto {task.replace('_', '-')} --config {path}",
        rule,
    ]
    return "\n".join(lines) + "\n"
